//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pagination.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class newstudent
    {
        string _rollnumber;
        string _first_name;
        string _last_name;
        string _email;
        string _gender;

        public int id { get; set; }
        public string rollnumber 
        { 
            get
            {
                return _rollnumber ?? "";
            }
            set
            {
                _rollnumber = value;
            }
        }
        public string first_name 
        {
            get
            {
                return _first_name ?? "";
            }
            set
            {
                _first_name = value;
            }
        }
        public string last_name
        {
            get
            {
                return _last_name ?? "";
            }
            set
            {
                _last_name = value;
            }
        }
        public string email
        {
            get
            {
                return _email ?? "";
            }
            set
            {
                _email = value;
            }
        }
        public string gender
        {
            get
            {
                return _gender ?? "M";
            }
            set
            {
                _gender = value;
            }
        }
        public int marks { get; set; }

        public object this[string propertyName]
        {
            get
            {
                switch (propertyName)
                {
                    /* these are dynamic based on the the feed */
                    case "rollnumber": return rollnumber;
                    case "first_name": return first_name;
                    case "last_name": return last_name;
                    case "email": return email;
                    /* fixed default */
                    default: return rollnumber;
                }
            }
        }
    }
}
